# Generated by Django 5.0.1 on 2024-01-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="名")),
                ("last_name", models.CharField(max_length=30, verbose_name="姓")),
                ("age", models.IntegerField(verbose_name="年齢")),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=255, verbose_name="ニックネーム"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="組織名")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="placticeapp.person",
                        verbose_name="人",
                    ),
                ),
            ],
        ),
    ]
